media:
  input: src/media
  output: media

content:
  - name: posts
    label: Posts
    path: src/_posts
    type: collection
    view:
      fields: [ title, date, published ]
      sort: [ date, title, published ]
      default:
        search: 'author:Sam'
        sort: date, desc

  - name: authors
    label: Authors
    path: src/_data/authors.json
    type: file