media:
  input: src/media
  output: media

content:
  - name: posts
    label: Posts
    path: src/_posts
    type: collection
    fields: [ "title", "published", "tags[0]", "author.name" ]

  - name: authors
    label: Authors
    path: src/_data/authors.json
    type: file
    fields: [ author, name, title, phone, email, url ]

  